name: Exploring Variable and Secrets

on:
    push:

################ define environment variables at Workflow level #################

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: echo docker build -t $CONTAINER_REGISTRY//$IMAGE_NAME:latest

            - name: Docker Login
              env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: echo docker login --username=${{ vars.DOCKER_USERNAME}} --password=${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: echo docker run -d -p 80:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

################# define environment variables at Job level #################

# jobs:
#     docker:
#         runs-on: ubuntu-latest
#         env:
#             CONTAINER_REGISTRY: docker.io
#             {{vars.DOCKER_USERNAME}}: chandansinha20
#             IMAGE_NAME: github-actions-nginx
#         steps:
#         - name: Docker Build
#           run: docker build -t $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

#         - name: Docker Login
#           env:
#             DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#           run: docker login --username=${{vars.DOCKER_USERNAME}} --password=$DOCKER_PASSWORD

#         - name: Docker Publish
#           run: echo docker push $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         env:
#             CONTAINER_REGISTRY: docker.io
#             {{vars.DOCKER_USERNAME}}: chandansinha20
#             IMAGE_NAME: github-actions-nginx
#         steps:
#         - name: Docker Run
#           run: docker run -d -p 80:80 $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
################# define environment variables at step level #################
# jobs:
#     docker:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Build
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 {{vars.DOCKER_USERNAME}}: chandansinha20
#                 IMAGE_NAME: github-actions-nginx
#               run: docker build -t $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

#             - name: Docker Login
#               env:
#                 {{vars.DOCKER_USERNAME}}: chandansinha20
#                 DOCKER_PASSWORD: 
#               run: docker login --username=${{vars.DOCKER_USERNAME}} --password=$DOCKER_PASSWORD

#             - name: Docker Publish
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 {{vars.DOCKER_USERNAME}}: chandansinha20
#                 IMAGE_NAME: github-actions-nginx
#               run: echo docker push $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Run
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 {{vars.DOCKER_USERNAME}}: chandansinha20
#                 IMAGE_NAME: github-actions-nginx
#               run: docker run -d -p 80:80 $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest